name: Weekly Release Snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Update submodules
        run: ./update-submodules.sh

      - name: Create snapshot
        run: ./create-snapshot.sh

      - uses: actions/upload-artifact@v3
        with:
          name: snapshot.zip
          path: snapshot.zip
  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: snapshot.zip
